language: common-lisp
sudo: required

env:
  matrix:
    - LISP=sbcl
    - LISP=sbcl PGVERSION=9.6

install:
  - ./.travis.sh pgdg_repositories
  - ./.travis.sh postgresql_install
  - sudo apt-get install -y unzip libsqlite3-dev gawk freetds-dev
  - ./.travis.sh sbcl_install

before_script:
  - PGUSER=postgres createuser -S -R -D -E -l pgloader
  - PGUSER=postgres createdb -E UTF8 -O pgloader pgloader
  - PGUSER=postgres psql -d pgloader -c "create extension ip4r;"
  - PGUSER=pgloader psql -d pgloader -c "create schema expected;"
  - PGUSER=pgloader psql -d pgloader -c "create schema err;"
  - make --version
  - make

script:
  - PGUSER=pgloader make check

notifications:
  email:
    - dim@tapoueh.org
